<Project>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
    <InvariantGlobalization>true</InvariantGlobalization>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Diego Gerardo Larrosa</Authors>
    <Copyright>Copyright (c) 2026 Diego Gerardo Larrosa</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/diegolarrosa/Fanout</RepositoryUrl>
    <PackageProjectUrl>https://github.com/diegolarrosa/Fanout</PackageProjectUrl>
  </PropertyGroup>

</Project>
